// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Claw.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED
#include "../Commands/ClawToVertical.h"
// END AUTOGENERATED

Claw::Claw() : Subsystem("Claw") {
	// BEGIN AUTOGENERATED
	bite = RobotMap::bite;
	paradeState = RobotMap::paradeState;
	chargeState = RobotMap::chargeState;

    // END AUTOGENERATED
}

void Claw::Stop(){
	bite->Set(0.0);
}

void Claw::ClawBaseMove(int direction){
		bite->Set(RobotMap::biteRate*direction);
}

void Claw::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED
	SetDefaultCommand(new ClawToVertical());

    // END AUTOGENERATED
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

