// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef MECDRIVE_H
#define MECDRIVE_H

#include "Commands/PIDSubsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author Jude Sauve 2015
 */
class MecDrive: public PIDSubsystem {
private:
	float refAngle, rotation;
	float DynamicTarget(float turn);
 public:
	// BEGIN AUTOGENERATED
	Gyro* gyro;
	//AnalogInput* sonic;
	SpeedController* driveFL;
	SpeedController* driveFR;
	SpeedController* driveBL;
	SpeedController* driveBR;
	RobotDrive* baseDrive;

    // END AUTOGENERATED
	MecDrive();
	double ReturnPIDInput();
	void UsePIDOutput(double output);
	void InitDefaultCommand();
	void MecanumDrive(float x, float y, float turn);
	void MecanumDrive(float x, float y, float turn, bool gyroLess);
	void StopDrive();
	void ResetRefAngle();
	float FourB2VRota(bool lFast, bool lSlow, bool rSlow, bool rFast, bool gyroLess);
	float FourB2VRota(bool lFast, bool lSlow, bool rSlow, bool rFast);
};

#endif
