// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "MoveClawUp.h"

MoveClawUp::MoveClawUp() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED
	Requires(Robot::claw);

    // END AUTOGENERATED
}

// Called just before this Command runs the first time
void MoveClawUp::Initialize() {
	if(Robot::claw->paradeState)
			MoveClawUp::IsFinished();
}

// Called repeatedly when this Command is scheduled to run
void MoveClawUp::Execute() {
	Robot::claw->ClawBaseMove(RobotMap::directionP);
}

// Make this return true when this Command no longer needs to run execute()
bool MoveClawUp::IsFinished() {
	return (Robot::claw->paradeState||!Robot::oi->clawUp);
}

// Called once after isFinished returns true
void MoveClawUp::End() {
	Robot::claw->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void MoveClawUp::Interrupted() {
	Robot::claw->Stop();
}
