// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
public:
	// BEGIN AUTOGENERATED
	Joystick* stick;
	JoystickButton* downArm;
	JoystickButton* upArm;
	JoystickButton* armRoundH;
	JoystickButton* armToCan;
	JoystickButton* armDown1;
	JoystickButton* armUp1;
	JoystickButton* maxUsefulH;
	JoystickButton* totePlusStepLevel;
	JoystickButton* toteLevel;
	JoystickButton* clawUp;
	JoystickButton* clawDown;
	JoystickButton* clawOut;
	JoystickButton* clawNeutral;
    // END AUTOGENERATED

	OI();

	float deadbandKill(float init, float deadZone);

	JoystickButton* turnR_Fast;
	JoystickButton* turnR_Slow;
	JoystickButton* turnL_Fast;
	JoystickButton* turnL_Slow;
	JoystickButton* resetGyro;
	JoystickButton* gyroLess;
 
	// BEGIN AUTOGENERATED

	Joystick* getstick();

    // END AUTOGENERATED
};

#endif
