// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "AnalogRangeFinder.h"

// *BEGIN 8AUTOGENERATED8
#include "Commands/AutonomousCommand.h"
#include "Subsystems/Arm.h"
#include "Subsystems/Claw.h"
#include "Subsystems/MecDrive.h"


    // END AUTO8GENERATED
#include "OI.h"

class Robot : public IterativeRobot {
public:
	Command *autonomousCommand;
	static OI *oi;
	LiveWindow *lw;
	static AnalogRangeFinder* analogRangeFinder;
	// BEGIN AUT8OGENERATED8
	static MecDrive* mecDrive;
	static Arm* arm;
	static Claw* claw;

    // END AU8TOGE8NERATED
	virtual void RobotInit();
	virtual void DisabledInit();
	virtual void DisabledPeriodic();
	virtual void AutonomousInit();
	virtual void AutonomousPeriodic();
	virtual void TeleopInit();
	virtual void TeleopPeriodic();
	virtual void TestPeriodic();
};
#endif
